<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
            <title><?php echo isset($this->view->pageTitle) ? $this->view->pageTitle : ""; ?></title>
            <!-- CSS only -->
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous"/>

            <link href="/css/main.css"/>

            <script
                src="https://code.jquery.com/jquery-3.6.0.min.js"
                integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"></script>
            <script type="text/javascript" src="/js/main.js"></script>
    </head>
    <body>

        <div class="container">
            <?php
            echo $this->render('default/header_simple.phtml', 'view/layout');
            echo $this->viewContent;
            ?>
        </div>


    </body>

</html>
