
<div class="products row col-lg-12">
    <?php foreach ($this->view->products as $product): ?>
        <div class="col-lg-3 p-3 product-item">
            <div><img src="/img/default.jpg" width="150px"/></div>
            <div product-item-name="1">Product: <?= $product['name'] ?></div>
            <div product-item-price="1">Price: <?= $product['price'] ?></div>
            <?php if(isset($product['quantity']) && $product['quantity']>0):?>
            <div>Qty:<?= $product['quantity']; ?></div>
            <?php endif; ?>
            <div>
                <button type="button" class="btn btn-success add-product" data-value="<?= $product['id']; ?>">+</button>
                <button type="button" class="btn btn-danger remove-product" data-value="<?= $product['id']; ?>">-</button>
                <a href="/product/add_edit?id=<?= $product['id']; ?>">edit</a>
            </div>
        </div>
    <?php endforeach; ?>
</div>