<hr/>
<div class="row col-lg-12 p-3">
    <div class="col-lg-2 row">
        <a href="/test/alltests">
            <button type="button" class="btn btn-success">Run tests</button> 
        </a>
    </div>
    <div class="col-lg-2 row">
        <a href="/product/add_edit">
            <button type="button" class="btn btn-secondary">Add product</button>
        </a>
    </div>
    <div class="col-lg-8 row ">
    <div class="col-lg-12">
        <a href="https://github.com/iivanova" target="_blank" style="float:right;">
            iivanova 
        </a>
    </div>
    </div>
</div>